### ISSUE TITLE
Deprecated option used in docs

### ISSUE THREAD

**Issue by jdillard** [errata-ai/vale.sh#26]
[`code`](https://github.com/errata-ai/vale.sh/blob/73e6db660bc10059708288e430488cc3d125b62d/content/en/docs/topics/styles/index.md?plain=1#L124) is used in the [Existence](https://vale.sh/docs/topics/styles/#existence) example, but has since been deprecated.

**Comment by cadamini** [comment]
In https://studio.vale.sh, the example leads to 

> [2.25.2] [4:1]: has invalid keys: 'code'

I haven't found the ref to the deprecation.

**Comment by cadamini** [comment]
Fixed by https://github.com/errata-ai/vale.sh/commit/f80687251908273d37f53983e555a0838f6e632b
