### ISSUE TITLE
Vale sync issue

### ISSUE THREAD

**Issue by soaand01** [errata-ai/vale.sh#33]
Get a Vale issue during sync.

```
E201 Invalid value provided [/home/soaand01/labs/valeTest/styles/Microsoft/.travis.yml:1:1]:

   1* language: python
   2  cache: bundler
   3  python:

Missing the required 'extends' key.
```
It's actually not clear for me since it's a yml file it's not clear what the sync is expecting.
Can you help me for that ?

**Comment by jdkato** [comment]
Your `StylesPath` is misconfigured.

It appears that you have the entire `Microsoft` repo under `styles` when you only need the `Microsoft/Microsoft` subdirectory:

```
├── .git
├── .gitignore
├── .travis.yml
├── .yamllint.yml
├── CHANGELOG.md
├── Gemfile
├── LICENSE
├── Microsoft <-- You want this
├── README.md
├── coverage
├── features
├── fixtures
└── tmp
```

You can find this attached as a `.zip` on the [releases](https://github.com/errata-ai/Microsoft/releases/tag/v0.9.0).
