### ISSUE TITLE
preview shows doks rather than vale

### ISSUE THREAD

**Issue by edavidaja** [errata-ai/vale.sh#5]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/12927842/167470948-2e14dc65-36e1-4a70-a892-199185495d6d.png">

I saw this initially in slack when sharing Vale with some colleagues but tested in telegram as well; same issue.

**Comment by jdkato** [comment]
Thanks for the report.

It may take a few hours to update, but it should look something like this now:

![Screen Shot 2022-05-09 at 11 39 24 AM](https://user-images.githubusercontent.com/8785025/167475781-124dd3ff-885d-494f-bc87-ea436ff41685.png)
