### ISSUE TITLE
Question: How and how often is the Hub updated?

### ISSUE THREAD

**Issue by karl-johan-grahn** [errata-ai/vale.sh#51]
General question: How often is the Hub updated? https://github.com/errata-ai/vale.sh/blob/master/data/configs.yml has lots of entries that are not yet available on https://vale.sh/hub/, and I cannot see in the workflow how it is updated?

**Comment by jdkato** [comment]
Those are just open-source example configurations (of varying quality).

They won't be available in the Package Hub unless they are [submitted as such here](https://github.com/errata-ai/packages).
