### ISSUE TITLE
Quickstart docs on macOS: Not creating a `styles` folder before running `vale sync` saves styles  in Application folder

### ISSUE THREAD

**Issue by JohannesDienst-askui** [errata-ai/vale.sh#55]
Hello,

I followed the Quickstart guide and when I ran `vale sync` in my repository, it placed the downloaded styles into `/Users/<my username>/Library/Application Support/vale/styles` which is not what I expected.

When I first create the `styles` folder in my repository it places them inside the created folder.

Here is my `.vale.ini`:

```
StylesPath = styles

MinAlertLevel = suggestion

Packages = Google, alex

[*]
BasedOnStyles = Vale, Google, alex
```

If you accept PRs I can also create one for it, so the docs mention this behaviour 😃 .

Link to Quick Start source: https://github.com/errata-ai/vale.sh/blob/25233d62389af1fc49ce4792892be564061b76a6/content/en/docs/vale-cli/structure/index.md?plain=1#L27

**Comment by jdkato** [comment]
This is https://github.com/errata-ai/vale/issues/788; it's going to be fixed in the next release.
